// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package db

import (
	"context"
)

const createCustomerAction = `-- name: CreateCustomerAction :one
INSERT INTO customer_actions (
  customer_id,
  type,
  comments
) VALUES (
  $1,
  $2,
  $3
)
RETURNING
  id,
  customer_id,
  type,
  comments,
  action_date,
  created_at
`

type CreateCustomerActionParams struct {
	CustomerID int64
	Type       CustomerActionType
	Comments   string
}

func (q *Queries) CreateCustomerAction(ctx context.Context, arg CreateCustomerActionParams) (CustomerAction, error) {
	row := q.db.QueryRow(ctx, createCustomerAction, arg.CustomerID, arg.Type, arg.Comments)
	var i CustomerAction
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Type,
		&i.Comments,
		&i.ActionDate,
		&i.CreatedAt,
	)
	return i, err
}
