// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerAction = `-- name: CreateCustomerAction :one
INSERT INTO customer_actions (
  customer_id,
  type,
  comments,
  informant_name
) VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING
  id,
  customer_id,
  type,
  comments,
  informant_name,
  action_date,
  created_at
`

type CreateCustomerActionParams struct {
	CustomerID    int64
	Type          CustomerActionType
	Comments      string
	InformantName pgtype.Text
}

func (q *Queries) CreateCustomerAction(ctx context.Context, arg CreateCustomerActionParams) (CustomerAction, error) {
	row := q.db.QueryRow(ctx, createCustomerAction,
		arg.CustomerID,
		arg.Type,
		arg.Comments,
		arg.InformantName,
	)
	var i CustomerAction
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Type,
		&i.Comments,
		&i.InformantName,
		&i.ActionDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomerAction = `-- name: DeleteCustomerAction :execrows
DELETE FROM customer_actions
WHERE id = $1
  AND customer_id = $2
`

type DeleteCustomerActionParams struct {
	ID         int64
	CustomerID int64
}

func (q *Queries) DeleteCustomerAction(ctx context.Context, arg DeleteCustomerActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCustomerAction, arg.ID, arg.CustomerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCustomerActionsLastThreeMonths = `-- name: ListCustomerActionsLastThreeMonths :many
SELECT
  id,
  customer_id,
  type,
  comments,
  informant_name,
  action_date,
  created_at
FROM customer_actions
WHERE customer_id = $1
  AND action_date >= NOW() - INTERVAL '3 months'
ORDER BY action_date DESC, id DESC
`

func (q *Queries) ListCustomerActionsLastThreeMonths(ctx context.Context, customerID int64) ([]CustomerAction, error) {
	rows, err := q.db.Query(ctx, listCustomerActionsLastThreeMonths, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerAction
	for rows.Next() {
		var i CustomerAction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Type,
			&i.Comments,
			&i.InformantName,
			&i.ActionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerActionComments = `-- name: UpdateCustomerActionComments :one
UPDATE customer_actions
SET comments = $1
WHERE id = $2
  AND customer_id = $3
RETURNING
  id,
  customer_id,
  type,
  comments,
  informant_name,
  action_date,
  created_at
`

type UpdateCustomerActionCommentsParams struct {
	Comments   string
	ID         int64
	CustomerID int64
}

func (q *Queries) UpdateCustomerActionComments(ctx context.Context, arg UpdateCustomerActionCommentsParams) (CustomerAction, error) {
	row := q.db.QueryRow(ctx, updateCustomerActionComments, arg.Comments, arg.ID, arg.CustomerID)
	var i CustomerAction
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Type,
		&i.Comments,
		&i.InformantName,
		&i.ActionDate,
		&i.CreatedAt,
	)
	return i, err
}
