// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearCustomerReview = `-- name: ClearCustomerReview :one
UPDATE customers
SET
  reviewed_at = NULL,
  reviewed_until = NULL,
  reviewed_by = NULL
WHERE id = $1
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
`

func (q *Queries) ClearCustomerReview(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, clearCustomerReview, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*)::int
FROM customers
WHERE deactivated = FALSE
`

func (q *Queries) CountCustomers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCustomersDebt = `-- name: CountCustomersDebt :one
SELECT COUNT(*)::int
FROM customers c
WHERE c.deactivated = FALSE
  AND (
    cardinality($1::text[]) = 0
    OR c.company_type::text = ANY($1::text[])
  )
  AND (
    $2::text = ''
    OR c.company_name ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::boolean
    OR
    c.reviewed_until IS NULL
    OR c.reviewed_until <= NOW()
  )
`

type CountCustomersDebtParams struct {
	CompanyTypes    []string
	CompanyName     string
	IncludeReviewed bool
}

func (q *Queries) CountCustomersDebt(ctx context.Context, arg CountCustomersDebtParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCustomersDebt, arg.CompanyTypes, arg.CompanyName, arg.IncludeReviewed)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
`

type CreateCustomerParams struct {
	CompanyName      string
	CompanyType      CompanyType
	Phone            string
	Email            string
	MonthlyFee       int32
	BillingStartedAt pgtype.Date
	Comments         string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyName,
		arg.CompanyType,
		arg.Phone,
		arg.Email,
		arg.MonthlyFee,
		arg.BillingStartedAt,
		arg.Comments,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
FROM customers
WHERE deactivated = FALSE
ORDER BY id
LIMIT $2
OFFSET $1
`

type ListCustomersParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.Phone,
			&i.Email,
			&i.MonthlyFee,
			&i.BillingStartedAt,
			&i.Comments,
			&i.Deactivated,
			&i.ReviewedAt,
			&i.ReviewedUntil,
			&i.ReviewedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersDebt = `-- name: ListCustomersDebt :many
WITH customer_debts AS (
  SELECT
    c.id,
    c.company_name,
    c.company_type,
    c.monthly_fee,
    c.billing_started_at,
    c.comments,
    c.deactivated,
    c.reviewed_at,
    c.reviewed_until,
    c.reviewed_by,
    COUNT(overdue_months.month_date)::int AS overdue_months,
    (COUNT(overdue_months.month_date) * c.monthly_fee)::bigint AS overdue_amount
  FROM customers c
  LEFT JOIN LATERAL (
    SELECT
      month_date
    FROM generate_series(
      date_trunc('month', c.billing_started_at)::date,
      date_trunc('month', CURRENT_DATE)::date,
      INTERVAL '1 month'
    ) AS month_date
    LEFT JOIN customer_payments cp
      ON cp.customer_id = c.id
     AND cp.year = EXTRACT(YEAR FROM month_date)::int
     AND cp.month = EXTRACT(MONTH FROM month_date)::int
    WHERE cp.id IS NULL
      AND (
        month_date::date +
        (
          LEAST(
            $5::int,
            EXTRACT(
              DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
            )::int
          ) - 1
        ) * INTERVAL '1 day'
      )::date < CURRENT_DATE
  ) overdue_months ON true
  WHERE c.deactivated = FALSE
    AND (
      cardinality($6::text[]) = 0
      OR c.company_type::text = ANY($6::text[])
    )
    AND (
      $7::text = ''
      OR c.company_name ILIKE '%' || $7::text || '%'
    )
    AND (
      $8::boolean
      OR
      c.reviewed_until IS NULL
      OR c.reviewed_until <= NOW()
    )
  GROUP BY c.id
)
SELECT
  id,
  company_name,
  company_type,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  overdue_months,
  overdue_amount
FROM customer_debts
ORDER BY
  CASE WHEN $1::text = 'amount' AND $2::text = 'asc' THEN overdue_amount END ASC,
  CASE WHEN $1::text = 'amount' AND $2::text = 'desc' THEN overdue_amount END DESC,
  CASE WHEN $1::text = 'months' AND $2::text = 'asc' THEN overdue_months END ASC,
  CASE WHEN $1::text = 'months' AND $2::text = 'desc' THEN overdue_months END DESC,
  overdue_amount DESC,
  overdue_months DESC,
  id ASC
LIMIT $4
OFFSET $3
`

type ListCustomersDebtParams struct {
	SortBy          string
	SortDirection   string
	Offset          int32
	Limit           int32
	DueDay          int32
	CompanyTypes    []string
	CompanyName     string
	IncludeReviewed bool
}

type ListCustomersDebtRow struct {
	ID               int64
	CompanyName      string
	CompanyType      CompanyType
	MonthlyFee       int32
	BillingStartedAt pgtype.Date
	Comments         string
	Deactivated      bool
	ReviewedAt       pgtype.Timestamptz
	ReviewedUntil    pgtype.Timestamptz
	ReviewedBy       pgtype.Text
	OverdueMonths    int32
	OverdueAmount    int64
}

func (q *Queries) ListCustomersDebt(ctx context.Context, arg ListCustomersDebtParams) ([]ListCustomersDebtRow, error) {
	rows, err := q.db.Query(ctx, listCustomersDebt,
		arg.SortBy,
		arg.SortDirection,
		arg.Offset,
		arg.Limit,
		arg.DueDay,
		arg.CompanyTypes,
		arg.CompanyName,
		arg.IncludeReviewed,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersDebtRow
	for rows.Next() {
		var i ListCustomersDebtRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.MonthlyFee,
			&i.BillingStartedAt,
			&i.Comments,
			&i.Deactivated,
			&i.ReviewedAt,
			&i.ReviewedUntil,
			&i.ReviewedBy,
			&i.OverdueMonths,
			&i.OverdueAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomerReviewed = `-- name: MarkCustomerReviewed :one
UPDATE customers
SET
  reviewed_at = NOW(),
  reviewed_until = NOW() + ($1::int * INTERVAL '1 day'),
  reviewed_by = NULLIF(BTRIM($2::text), '')
WHERE id = $3
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
`

type MarkCustomerReviewedParams struct {
	Days       int32
	ReviewedBy string
	ID         int64
}

func (q *Queries) MarkCustomerReviewed(ctx context.Context, arg MarkCustomerReviewedParams) (Customer, error) {
	row := q.db.QueryRow(ctx, markCustomerReviewed, arg.Days, arg.ReviewedBy, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCustomerComments = `-- name: UpdateCustomerComments :one
UPDATE customers
SET comments = $1
WHERE id = $2
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
`

type UpdateCustomerCommentsParams struct {
	Comments string
	ID       int64
}

func (q *Queries) UpdateCustomerComments(ctx context.Context, arg UpdateCustomerCommentsParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerComments, arg.Comments, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCustomerContact = `-- name: UpdateCustomerContact :one
UPDATE customers
SET
  phone = $1,
  email = $2,
  monthly_fee = $3
WHERE id = $4
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
`

type UpdateCustomerContactParams struct {
	Phone      string
	Email      string
	MonthlyFee int32
	ID         int64
}

func (q *Queries) UpdateCustomerContact(ctx context.Context, arg UpdateCustomerContactParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerContact,
		arg.Phone,
		arg.Email,
		arg.MonthlyFee,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCustomerDeactivated = `-- name: UpdateCustomerDeactivated :one
UPDATE customers
SET deactivated = $1
WHERE id = $2
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  comments,
  deactivated,
  reviewed_at,
  reviewed_until,
  reviewed_by,
  created_at
`

type UpdateCustomerDeactivatedParams struct {
	Deactivated bool
	ID          int64
}

func (q *Queries) UpdateCustomerDeactivated(ctx context.Context, arg UpdateCustomerDeactivatedParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerDeactivated, arg.Deactivated, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.Comments,
		&i.Deactivated,
		&i.ReviewedAt,
		&i.ReviewedUntil,
		&i.ReviewedBy,
		&i.CreatedAt,
	)
	return i, err
}
