// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*)::int
FROM customers
`

func (q *Queries) CountCustomers(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCustomersByCompanyName = `-- name: CountCustomersByCompanyName :one
SELECT COUNT(*)::int
FROM customers
WHERE company_name ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountCustomersByCompanyName(ctx context.Context, companyName string) (int32, error) {
	row := q.db.QueryRow(ctx, countCustomersByCompanyName, companyName)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countCustomersDebt = `-- name: CountCustomersDebt :one
SELECT COUNT(*)::int
FROM customers c
WHERE cardinality($1::text[]) = 0
   OR c.company_type::text = ANY($1::text[])
`

func (q *Queries) CountCustomersDebt(ctx context.Context, companyTypes []string) (int32, error) {
	row := q.db.QueryRow(ctx, countCustomersDebt, companyTypes)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  created_at
`

type CreateCustomerParams struct {
	CompanyName      string
	CompanyType      CompanyType
	Phone            string
	Email            string
	MonthlyFee       pgtype.Numeric
	BillingStartedAt pgtype.Date
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyName,
		arg.CompanyType,
		arg.Phone,
		arg.Email,
		arg.MonthlyFee,
		arg.BillingStartedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.BillingStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  created_at
FROM customers
ORDER BY id
LIMIT $2
OFFSET $1
`

type ListCustomersParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.Phone,
			&i.Email,
			&i.MonthlyFee,
			&i.BillingStartedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersDebt = `-- name: ListCustomersDebt :many
WITH customer_debts AS (
  SELECT
    c.id,
    c.company_name,
    c.company_type,
    c.phone,
    c.email,
    c.monthly_fee,
    c.billing_started_at,
    COUNT(overdue_months.month_date)::int AS overdue_months,
    COALESCE(SUM(c.monthly_fee), 0)::numeric AS overdue_amount
  FROM customers c
  LEFT JOIN LATERAL (
    SELECT
      month_date
    FROM generate_series(
      date_trunc('month', c.billing_started_at)::date,
      date_trunc('month', CURRENT_DATE)::date,
      INTERVAL '1 month'
    ) AS month_date
    LEFT JOIN customer_payments cp
      ON cp.customer_id = c.id
     AND cp.year = EXTRACT(YEAR FROM month_date)::int
     AND cp.month = EXTRACT(MONTH FROM month_date)::int
    WHERE cp.id IS NULL
      AND (
        month_date::date +
        (
          LEAST(
            $5::int,
            EXTRACT(
              DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
            )::int
          ) - 1
        ) * INTERVAL '1 day'
      )::date < CURRENT_DATE
  ) overdue_months ON true
  WHERE cardinality($6::text[]) = 0
     OR c.company_type::text = ANY($6::text[])
  GROUP BY c.id
)
SELECT
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  overdue_months,
  overdue_amount
FROM customer_debts
ORDER BY
  CASE WHEN $1::text = 'amount' AND $2::text = 'asc' THEN overdue_amount END ASC,
  CASE WHEN $1::text = 'amount' AND $2::text = 'desc' THEN overdue_amount END DESC,
  CASE WHEN $1::text = 'months' AND $2::text = 'asc' THEN overdue_months END ASC,
  CASE WHEN $1::text = 'months' AND $2::text = 'desc' THEN overdue_months END DESC,
  overdue_amount DESC,
  overdue_months DESC,
  id ASC
LIMIT $4
OFFSET $3
`

type ListCustomersDebtParams struct {
	SortBy        string
	SortDirection string
	Offset        int32
	Limit         int32
	DueDay        int32
	CompanyTypes  []string
}

type ListCustomersDebtRow struct {
	ID               int64
	CompanyName      string
	CompanyType      CompanyType
	Phone            string
	Email            string
	MonthlyFee       pgtype.Numeric
	BillingStartedAt pgtype.Date
	OverdueMonths    int32
	OverdueAmount    pgtype.Numeric
}

func (q *Queries) ListCustomersDebt(ctx context.Context, arg ListCustomersDebtParams) ([]ListCustomersDebtRow, error) {
	rows, err := q.db.Query(ctx, listCustomersDebt,
		arg.SortBy,
		arg.SortDirection,
		arg.Offset,
		arg.Limit,
		arg.DueDay,
		arg.CompanyTypes,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomersDebtRow
	for rows.Next() {
		var i ListCustomersDebtRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.Phone,
			&i.Email,
			&i.MonthlyFee,
			&i.BillingStartedAt,
			&i.OverdueMonths,
			&i.OverdueAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomersByCompanyName = `-- name: SearchCustomersByCompanyName :many
SELECT
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  billing_started_at,
  created_at
FROM customers
WHERE company_name ILIKE '%' || $1::text || '%'
ORDER BY company_name ASC, id ASC
LIMIT $3
OFFSET $2
`

type SearchCustomersByCompanyNameParams struct {
	CompanyName string
	Offset      int32
	Limit       int32
}

func (q *Queries) SearchCustomersByCompanyName(ctx context.Context, arg SearchCustomersByCompanyNameParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomersByCompanyName, arg.CompanyName, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.Phone,
			&i.Email,
			&i.MonthlyFee,
			&i.BillingStartedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
