// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
  company_name,
  company_type,
  phone,
  email,
  monthly_fee
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  created_at
`

type CreateCustomerParams struct {
	CompanyName string
	CompanyType CompanyType
	Phone       string
	Email       string
	MonthlyFee  pgtype.Numeric
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.CompanyName,
		arg.CompanyType,
		arg.Phone,
		arg.Email,
		arg.MonthlyFee,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.CompanyType,
		&i.Phone,
		&i.Email,
		&i.MonthlyFee,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT
  id,
  company_name,
  company_type,
  phone,
  email,
  monthly_fee,
  created_at
FROM customers
ORDER BY id
LIMIT $2
OFFSET $1
`

type ListCustomersParams struct {
	Offset int32
	Limit  int32
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.CompanyType,
			&i.Phone,
			&i.Email,
			&i.MonthlyFee,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
