// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyType string

const (
	CompanyTypeEnterprise CompanyType = "enterprise"
	CompanyTypePyme       CompanyType = "pyme"
	CompanyTypeStartup    CompanyType = "startup"
)

func (e *CompanyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyType(s)
	case string:
		*e = CompanyType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyType: %T", src)
	}
	return nil
}

type NullCompanyType struct {
	CompanyType CompanyType
	Valid       bool // Valid is true if CompanyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyType) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyType), nil
}

type CustomerActionType string

const (
	CustomerActionTypeCall          CustomerActionType = "call"
	CustomerActionTypeEmail         CustomerActionType = "email"
	CustomerActionTypePersonalVisit CustomerActionType = "personal_visit"
	CustomerActionTypeOther         CustomerActionType = "other"
)

func (e *CustomerActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomerActionType(s)
	case string:
		*e = CustomerActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomerActionType: %T", src)
	}
	return nil
}

type NullCustomerActionType struct {
	CustomerActionType CustomerActionType
	Valid              bool // Valid is true if CustomerActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomerActionType) Scan(value interface{}) error {
	if value == nil {
		ns.CustomerActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomerActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomerActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomerActionType), nil
}

type PaymentStatus string

const (
	PaymentStatusPending PaymentStatus = "pending"
	PaymentStatusPaid    PaymentStatus = "paid"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type Customer struct {
	ID               int64
	CompanyName      string
	CompanyType      CompanyType
	Phone            string
	Email            string
	MonthlyFee       pgtype.Numeric
	BillingStartedAt pgtype.Date
	Comments         string
	CreatedAt        pgtype.Timestamptz
}

type CustomerAction struct {
	ID         int64
	CustomerID int64
	Type       CustomerActionType
	Comments   string
	ActionDate pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type CustomerPayment struct {
	ID         int64
	CustomerID int64
	Year       int32
	Month      int32
	Status     PaymentStatus
	PaidAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}
