// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerPayment = `-- name: CreateCustomerPayment :one
INSERT INTO customer_payments (
  customer_id,
  year,
  month,
  status,
  paid_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  customer_id,
  year,
  month,
  status,
  paid_at,
  created_at
`

type CreateCustomerPaymentParams struct {
	CustomerID int64
	Year       int32
	Month      int32
	Status     PaymentStatus
	PaidAt     pgtype.Timestamptz
}

func (q *Queries) CreateCustomerPayment(ctx context.Context, arg CreateCustomerPaymentParams) (CustomerPayment, error) {
	row := q.db.QueryRow(ctx, createCustomerPayment,
		arg.CustomerID,
		arg.Year,
		arg.Month,
		arg.Status,
		arg.PaidAt,
	)
	var i CustomerPayment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalCustomerDebt = `-- name: GetTotalCustomerDebt :one
WITH customer_months AS (
  SELECT
    c.id AS customer_id,
    c.monthly_fee,
    EXTRACT(YEAR FROM month_date)::int AS year,
    EXTRACT(MONTH FROM month_date)::int AS month,
    (
      month_date::date +
      (
        LEAST(
          $1::int,
          EXTRACT(
            DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
          )::int
        ) - 1
      ) * INTERVAL '1 day'
    )::date AS due_date
  FROM customers c
  CROSS JOIN LATERAL generate_series(
    date_trunc('month', c.billing_started_at)::date,
    date_trunc('month', CURRENT_DATE)::date,
    INTERVAL '1 month'
  ) AS month_date
)
SELECT
  COALESCE(SUM(cm.monthly_fee), 0)::numeric AS total_debt
FROM customer_months cm
LEFT JOIN customer_payments cp
  ON cp.customer_id = cm.customer_id
 AND cp.year = cm.year
 AND cp.month = cm.month
WHERE cp.id IS NULL
  AND cm.due_date < CURRENT_DATE
`

func (q *Queries) GetTotalCustomerDebt(ctx context.Context, dueDay int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalCustomerDebt, dueDay)
	var total_debt pgtype.Numeric
	err := row.Scan(&total_debt)
	return total_debt, err
}

const listCustomerPaymentsLastYear = `-- name: ListCustomerPaymentsLastYear :many
SELECT
  id,
  customer_id,
  year,
  month,
  status,
  paid_at,
  created_at
FROM customer_payments
WHERE customer_id = $1
  AND make_date(year, month, 1) >= date_trunc('month', CURRENT_DATE)::date - INTERVAL '11 months'
  AND make_date(year, month, 1) <= date_trunc('month', CURRENT_DATE)::date
ORDER BY year DESC, month DESC
`

func (q *Queries) ListCustomerPaymentsLastYear(ctx context.Context, customerID int64) ([]CustomerPayment, error) {
	rows, err := q.db.Query(ctx, listCustomerPaymentsLastYear, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerPayment
	for rows.Next() {
		var i CustomerPayment
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
