// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerPayment = `-- name: CreateCustomerPayment :one
INSERT INTO customer_payments (
  customer_id,
  year,
  month,
  status,
  paid_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  customer_id,
  year,
  month,
  status,
  paid_at,
  created_at
`

type CreateCustomerPaymentParams struct {
	CustomerID int64
	Year       int32
	Month      int32
	Status     PaymentStatus
	PaidAt     pgtype.Timestamptz
}

func (q *Queries) CreateCustomerPayment(ctx context.Context, arg CreateCustomerPaymentParams) (CustomerPayment, error) {
	row := q.db.QueryRow(ctx, createCustomerPayment,
		arg.CustomerID,
		arg.Year,
		arg.Month,
		arg.Status,
		arg.PaidAt,
	)
	var i CustomerPayment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerDebtSummary = `-- name: GetCustomerDebtSummary :one
WITH customer_months AS (
  SELECT
    c.id AS customer_id,
    c.monthly_fee,
    EXTRACT(YEAR FROM month_date)::int AS year,
    EXTRACT(MONTH FROM month_date)::int AS month,
    (
      month_date::date +
      (
        LEAST(
          $1::int,
          EXTRACT(
            DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
          )::int
        ) - 1
      ) * INTERVAL '1 day'
    )::date AS due_date
  FROM customers c
  CROSS JOIN LATERAL generate_series(
    date_trunc('month', c.billing_started_at)::date,
    date_trunc('month', CURRENT_DATE)::date,
    INTERVAL '1 month'
  ) AS month_date
  WHERE c.id = $2
)
SELECT
  COUNT(customer_months.month)::int AS overdue_months,
  COALESCE(SUM(customer_months.monthly_fee), 0)::bigint AS overdue_amount
FROM customer_months
LEFT JOIN customer_payments cp
  ON cp.customer_id = customer_months.customer_id
 AND cp.year = customer_months.year
 AND cp.month = customer_months.month
WHERE customer_months.due_date < CURRENT_DATE
  AND (
    cp.id IS NULL
    OR cp.status <> 'paid'
  )
`

type GetCustomerDebtSummaryParams struct {
	DueDay     int32
	CustomerID int64
}

type GetCustomerDebtSummaryRow struct {
	OverdueMonths int32
	OverdueAmount int64
}

func (q *Queries) GetCustomerDebtSummary(ctx context.Context, arg GetCustomerDebtSummaryParams) (GetCustomerDebtSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCustomerDebtSummary, arg.DueDay, arg.CustomerID)
	var i GetCustomerDebtSummaryRow
	err := row.Scan(&i.OverdueMonths, &i.OverdueAmount)
	return i, err
}

const getCustomerDelinquencyRate = `-- name: GetCustomerDelinquencyRate :one
WITH active_customers AS (
  SELECT
    id,
    billing_started_at
  FROM customers
  WHERE date_trunc('month', billing_started_at)::date <= date_trunc('month', CURRENT_DATE)::date
),
overdue_customers AS (
  SELECT DISTINCT
    active_customers.id
  FROM active_customers
  CROSS JOIN LATERAL (
    SELECT
      month_date,
      EXTRACT(YEAR FROM month_date)::int AS year,
      EXTRACT(MONTH FROM month_date)::int AS month,
      (
        month_date::date +
        (
          LEAST(
            $1::int,
            EXTRACT(
              DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
            )::int
          ) - 1
        ) * INTERVAL '1 day'
      )::date AS due_date
    FROM generate_series(
      date_trunc('month', active_customers.billing_started_at)::date,
      date_trunc('month', CURRENT_DATE)::date,
      INTERVAL '1 month'
    ) AS month_date
  ) customer_months
  LEFT JOIN customer_payments cp
    ON cp.customer_id = active_customers.id
   AND cp.year = customer_months.year
   AND cp.month = customer_months.month
  WHERE customer_months.due_date < CURRENT_DATE
    AND (
      cp.id IS NULL
      OR cp.status <> 'paid'
    )
)
SELECT
  COUNT(active_customers.id)::int AS total_customers,
  COUNT(overdue_customers.id)::int AS overdue_customers,
  COALESCE(
    COUNT(overdue_customers.id)::double precision * 100 / NULLIF(COUNT(active_customers.id), 0),
    0
  )::double precision AS delinquency_percentage
FROM active_customers
LEFT JOIN overdue_customers
  ON overdue_customers.id = active_customers.id
`

type GetCustomerDelinquencyRateRow struct {
	TotalCustomers        int32
	OverdueCustomers      int32
	DelinquencyPercentage float64
}

func (q *Queries) GetCustomerDelinquencyRate(ctx context.Context, dueDay int32) (GetCustomerDelinquencyRateRow, error) {
	row := q.db.QueryRow(ctx, getCustomerDelinquencyRate, dueDay)
	var i GetCustomerDelinquencyRateRow
	err := row.Scan(&i.TotalCustomers, &i.OverdueCustomers, &i.DelinquencyPercentage)
	return i, err
}

const getCustomerMetrics = `-- name: GetCustomerMetrics :many
WITH company_types AS (
  SELECT unnest(enum_range(NULL::company_type)) AS company_type
),
customer_totals AS (
  SELECT COUNT(*)::int AS total_customers
  FROM customers
),
customers_by_type AS (
  SELECT
    company_type,
    COUNT(*)::int AS customers
  FROM customers
  GROUP BY company_type
),
customer_months AS (
  SELECT
    c.id AS customer_id,
    c.company_type,
    EXTRACT(YEAR FROM month_date)::int AS year,
    EXTRACT(MONTH FROM month_date)::int AS month,
    (
      month_date::date +
      (
        LEAST(
          $1::int,
          EXTRACT(
            DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
          )::int
        ) - 1
      ) * INTERVAL '1 day'
    )::date AS due_date
  FROM customers c
  CROSS JOIN LATERAL generate_series(
    date_trunc('month', c.billing_started_at)::date,
    date_trunc('month', CURRENT_DATE)::date,
    INTERVAL '1 month'
  ) AS month_date
),
debtor_customers AS (
  SELECT DISTINCT
    customer_months.customer_id,
    customer_months.company_type
  FROM customer_months
  LEFT JOIN customer_payments cp
    ON cp.customer_id = customer_months.customer_id
   AND cp.year = customer_months.year
   AND cp.month = customer_months.month
  WHERE customer_months.due_date < CURRENT_DATE
    AND (
      cp.id IS NULL
      OR cp.status <> 'paid'
    )
),
debtor_totals AS (
  SELECT COUNT(*)::int AS customers
  FROM debtor_customers
),
debtors_by_type AS (
  SELECT
    company_type,
    COUNT(*)::int AS customers
  FROM debtor_customers
  GROUP BY company_type
)
SELECT
  customer_totals.total_customers,
  COALESCE(debtor_totals.customers, 0)::int AS debtor_customers,
  COALESCE(
    COALESCE(debtor_totals.customers, 0)::double precision * 100 / NULLIF(customer_totals.total_customers, 0),
    0
  )::double precision AS debtor_percentage,
  company_types.company_type::text AS company_type,
  COALESCE(customers_by_type.customers, 0)::int AS type_customers,
  COALESCE(
    COALESCE(customers_by_type.customers, 0)::double precision * 100 / NULLIF(customer_totals.total_customers, 0),
    0
  )::double precision AS type_percentage,
  COALESCE(debtors_by_type.customers, 0)::int AS type_debtor_customers,
  COALESCE(
    COALESCE(debtors_by_type.customers, 0)::double precision * 100 / NULLIF(debtor_totals.customers, 0),
    0
  )::double precision AS type_debtor_percentage
FROM company_types
CROSS JOIN customer_totals
CROSS JOIN debtor_totals
LEFT JOIN customers_by_type
  ON customers_by_type.company_type = company_types.company_type
LEFT JOIN debtors_by_type
  ON debtors_by_type.company_type = company_types.company_type
ORDER BY company_types.company_type
`

type GetCustomerMetricsRow struct {
	TotalCustomers       int32
	DebtorCustomers      int32
	DebtorPercentage     float64
	CompanyType          string
	TypeCustomers        int32
	TypePercentage       float64
	TypeDebtorCustomers  int32
	TypeDebtorPercentage float64
}

func (q *Queries) GetCustomerMetrics(ctx context.Context, dueDay int32) ([]GetCustomerMetricsRow, error) {
	rows, err := q.db.Query(ctx, getCustomerMetrics, dueDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomerMetricsRow
	for rows.Next() {
		var i GetCustomerMetricsRow
		if err := rows.Scan(
			&i.TotalCustomers,
			&i.DebtorCustomers,
			&i.DebtorPercentage,
			&i.CompanyType,
			&i.TypeCustomers,
			&i.TypePercentage,
			&i.TypeDebtorCustomers,
			&i.TypeDebtorPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyDelinquencyRate = `-- name: GetMonthlyDelinquencyRate :many
WITH months AS (
  SELECT generate_series(1, 12)::int AS month
),
customer_months AS (
  SELECT
    months.month,
    c.id AS customer_id,
    (
      make_date($1::int, months.month, 1) +
      (
        LEAST(
          $2::int,
          EXTRACT(
            DAY FROM make_date($1::int, months.month, 1) + INTERVAL '1 month - 1 day'
          )::int
        ) - 1
      ) * INTERVAL '1 day'
    )::date AS due_date
  FROM months
  JOIN customers c
    ON date_trunc('month', c.billing_started_at)::date <= make_date($1::int, months.month, 1)
)
SELECT
  months.month,
  COUNT(customer_months.customer_id)::int AS total_customers,
  COUNT(customer_months.customer_id) FILTER (
    WHERE customer_payments.id IS NULL
       OR customer_payments.status <> 'paid'
       OR customer_payments.paid_at::date > customer_months.due_date
  )::int AS overdue_customers,
  COALESCE(
    COUNT(customer_months.customer_id) FILTER (
      WHERE customer_payments.id IS NULL
         OR customer_payments.status <> 'paid'
         OR customer_payments.paid_at::date > customer_months.due_date
    )::double precision * 100 / NULLIF(COUNT(customer_months.customer_id), 0),
    0
  )::double precision AS delinquency_percentage
FROM months
LEFT JOIN customer_months
  ON customer_months.month = months.month
 AND customer_months.due_date <= CURRENT_DATE
LEFT JOIN customer_payments
  ON customer_payments.customer_id = customer_months.customer_id
 AND customer_payments.year = $1::int
 AND customer_payments.month = months.month
GROUP BY months.month
ORDER BY months.month
`

type GetMonthlyDelinquencyRateParams struct {
	Year   int32
	DueDay int32
}

type GetMonthlyDelinquencyRateRow struct {
	Month                 int32
	TotalCustomers        int32
	OverdueCustomers      int32
	DelinquencyPercentage float64
}

func (q *Queries) GetMonthlyDelinquencyRate(ctx context.Context, arg GetMonthlyDelinquencyRateParams) ([]GetMonthlyDelinquencyRateRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyDelinquencyRate, arg.Year, arg.DueDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyDelinquencyRateRow
	for rows.Next() {
		var i GetMonthlyDelinquencyRateRow
		if err := rows.Scan(
			&i.Month,
			&i.TotalCustomers,
			&i.OverdueCustomers,
			&i.DelinquencyPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCustomerDebt = `-- name: GetTotalCustomerDebt :one
WITH customer_months AS (
  SELECT
    c.id AS customer_id,
    c.monthly_fee,
    EXTRACT(YEAR FROM month_date)::int AS year,
    EXTRACT(MONTH FROM month_date)::int AS month,
    (
      month_date::date +
      (
        LEAST(
          $1::int,
          EXTRACT(
            DAY FROM date_trunc('month', month_date)::date + INTERVAL '1 month - 1 day'
          )::int
        ) - 1
      ) * INTERVAL '1 day'
    )::date AS due_date
  FROM customers c
  CROSS JOIN LATERAL generate_series(
    date_trunc('month', c.billing_started_at)::date,
    date_trunc('month', CURRENT_DATE)::date,
    INTERVAL '1 month'
  ) AS month_date
)
SELECT
  COALESCE(SUM(cm.monthly_fee), 0)::bigint AS total_debt
FROM customer_months cm
LEFT JOIN customer_payments cp
  ON cp.customer_id = cm.customer_id
 AND cp.year = cm.year
 AND cp.month = cm.month
WHERE cp.id IS NULL
  AND cm.due_date < CURRENT_DATE
`

func (q *Queries) GetTotalCustomerDebt(ctx context.Context, dueDay int32) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalCustomerDebt, dueDay)
	var total_debt int64
	err := row.Scan(&total_debt)
	return total_debt, err
}

const listCustomerPaymentsLastYear = `-- name: ListCustomerPaymentsLastYear :many
SELECT
  id,
  customer_id,
  year,
  month,
  status,
  paid_at,
  created_at
FROM customer_payments
WHERE customer_id = $1
  AND make_date(year, month, 1) >= date_trunc('month', CURRENT_DATE)::date - INTERVAL '11 months'
  AND make_date(year, month, 1) <= date_trunc('month', CURRENT_DATE)::date
ORDER BY year DESC, month DESC
`

func (q *Queries) ListCustomerPaymentsLastYear(ctx context.Context, customerID int64) ([]CustomerPayment, error) {
	rows, err := q.db.Query(ctx, listCustomerPaymentsLastYear, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomerPayment
	for rows.Next() {
		var i CustomerPayment
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
