// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerPayment = `-- name: CreateCustomerPayment :one
INSERT INTO customer_payments (
  customer_id,
  year,
  month,
  status,
  paid_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING
  id,
  customer_id,
  year,
  month,
  status,
  paid_at,
  created_at
`

type CreateCustomerPaymentParams struct {
	CustomerID int64
	Year       int32
	Month      int32
	Status     PaymentStatus
	PaidAt     pgtype.Timestamptz
}

func (q *Queries) CreateCustomerPayment(ctx context.Context, arg CreateCustomerPaymentParams) (CustomerPayment, error) {
	row := q.db.QueryRow(ctx, createCustomerPayment,
		arg.CustomerID,
		arg.Year,
		arg.Month,
		arg.Status,
		arg.PaidAt,
	)
	var i CustomerPayment
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}
